server:
  port: 80

spring:
  profiles:
    active: ${profileActive}
  application:
    name: gateway-server
  redis:
    host: 122.51.171.126
    password: ak402507979
    port: 6379
    timeout: 5000
    lettuce:
      pool:
        max-idle: 5

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://106.12.208.53:3306/webuy_gateway?useUnicode=true&characterEncoding=UTF-8&allowMutiQueries=true
    username: user01
    password: ak402507979
    hikari:
      maxLifetime: 30000

  cloud:
    consul:
      host: 127.0.0.1
      discovery:
        prefer-ip-address: true
        instance-id: ${spring.application.name}:${spring.cloud.consul.discovery.ip-address}:${server.port}
        ip-address: 127.0.0.1
        health-check-path: /endpoint/_health
        health-check-critical-timeout: 10s
        health-check-interval: 3s

logging:
  config: classpath:config/logback/logback-spring.xml

mybatis:
  mapper-locations: classpath*:config/mybatis/mapper/**/*.xml

rocket-mq:
  name-server: 122.51.171.126:9876

